language: python
env:
 - PYTHONPATH=`pwd`
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - cd src/
  - python manage.py check
  - python manage.py migrate
script:
  - python manage.py test profiles
