language: python
env:
 - PYTHONPATH=`pwd`
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - cp src/sctvehcheck/settings/local.sample.env src/sctvehcheck/settings/local.env
  - cd src/
  - python manage.py migrate
  - cd ../
script:
  - python manage.py test profiles
