# Generated by Django 2.0.6 on 2018-06-09 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Persona/Empresa', max_length=150)),
                ('rfc', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='RFC')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'cliente',
                'ordering': ['-creado'],
                'get_latest_by': 'creado',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=120, null=True)),
                ('numero_interior', models.CharField(default='S/N', max_length=10, verbose_name='Número interior')),
                ('numero_exterior', models.CharField(default='S/N', max_length=10, verbose_name='Número exterior')),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('actual', models.BooleanField(default=True)),
                ('codigo_postal', models.IntegerField(blank=True, null=True, verbose_name='Código postal:')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiclecheck.Cliente')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
                'db_table': 'domicilio',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idmunicipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('idestado', models.ForeignKey(db_column='idestado', on_delete=django.db.models.deletion.CASCADE, to='vehiclecheck.Estado')),
            ],
            options={
                'verbose_name': 'municipio',
                'verbose_name_plural': 'municipios',
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre tipo')),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicio',
                'db_table': 'tiposervicio',
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(max_length=50, unique=True, verbose_name='Tipo')),
                ('numero_ejes', models.IntegerField(blank=True, null=True, verbose_name='No. Ejes')),
            ],
            options={
                'verbose_name': 'Tipo de vehículo',
                'verbose_name_plural': 'Tipos de vehículos',
                'db_table': 'tipovehiculo',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=25, verbose_name='Placas')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=25, null=True)),
                ('anho_modelo', models.IntegerField(verbose_name='Año modelo')),
                ('serie', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='No. Serie o NIV')),
                ('capacidad_kg', models.IntegerField(default=0, verbose_name='Capacidad (kg)')),
                ('capacidad_lt', models.IntegerField(default=0, verbose_name='Capacidad (litros)')),
                ('capacidad_personas', models.IntegerField(default=0, verbose_name='Capacidad (pasajeros)')),
                ('tarjeta_circulacion', models.CharField(default='N/A', max_length=25, verbose_name='Tarjeta circulación')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiclecheck.Cliente')),
                ('creado_por', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiclecheck.TipoVehiculo', verbose_name='Tipo de Vehículo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
                'ordering': ['-creado'],
                'get_latest_by': 'creado',
            },
        ),
        migrations.CreateModel(
            name='VerificacionVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(default='desconocido', max_length=15, unique=True)),
                ('no_aprobacion', models.CharField(max_length=25, verbose_name='No. Aprobación')),
                ('no_acreditacion', models.CharField(max_length=25, verbose_name='No. Acreditación')),
                ('semestre', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=1)),
                ('resultado', models.CharField(choices=[('APROBADO', 'APROBADO'), ('CANCELADO', 'CANCELADO'), ('RECHAZADO', 'RECHAZADO')], default='CANCELADO', max_length=10)),
                ('estado_vehiculo', models.CharField(choices=[('V', 'VACÍO'), ('C', 'CARGADO')], default='V', max_length=1, verbose_name='Estado vehículo')),
                ('observaciones', models.TextField(blank=True)),
                ('odometro', models.CharField(default='N/A', help_text='kilometraje del vehículo', max_length=15, verbose_name='Odómetro')),
                ('fecha_verificacion', models.DateField(verbose_name='Fecha verificación')),
                ('fv_string', models.CharField(default='2018-06-09', editable=False, max_length=10)),
                ('fecha_verificacion_anterior', models.DateField(blank=True, null=True, verbose_name='Verificación anterior')),
                ('fva_string', models.CharField(default='2018-06-09', editable=False, max_length=10)),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hi_string', models.CharField(default='06:27', editable=False, max_length=10)),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('hf_string', models.CharField(default='06:27', editable=False, max_length=10)),
                ('tecnico_verificador', models.CharField(max_length=75, verbose_name='Técnico verificador')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tipo_servicio', models.ForeignKey(default='SS', on_delete=django.db.models.deletion.SET_DEFAULT, to='vehiclecheck.TipoServicio', verbose_name='Tipo servicio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiclecheck.Vehiculo')),
            ],
            options={
                'verbose_name': 'Verificación vehicular',
                'verbose_name_plural': 'Verificaciones vehiculares',
                'db_table': 'verificacion',
                'ordering': ['-fecha_verificacion'],
                'get_latest_by': 'fecha_verificacion',
            },
        ),
        migrations.AddField(
            model_name='domicilio',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiclecheck.Estado'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='idestado', on_delete=django.db.models.deletion.CASCADE, to='vehiclecheck.Municipio'),
        ),
    ]
