# Generated by Django 2.0.6 on 2018-06-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sitio', models.CharField(default='Nombre del sistema o sitio', max_length=255, verbose_name='Nombre del sitio')),
                ('empresa', models.CharField(default='Nombre empresa', max_length=255, verbose_name='Nombre de la empresa')),
                ('mode_mantenimiento', models.BooleanField(default=False, verbose_name='Modo mantenimiento')),
                ('no_aprobacion', models.CharField(default='UV/SCT/CFM/14/016', max_length=25, verbose_name='No. Aprobación')),
                ('no_acreditacion', models.CharField(default='UVSCTAT016', max_length=25, verbose_name='No. Acreditación')),
            ],
            options={
                'verbose_name': 'Sistema',
            },
        ),
    ]
